@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue May 05 21:02:52 -0500 2026
REM SW Build 5239630 on Fri Nov 08 22:35:27 MST 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim Top_tb_behav -key {Behavioral:sim_1:Functional:Top_tb} -tclbatch Top_tb.tcl -view C:/Users/night/Desktop/EECS443-FinalProject/waveform_generator/Top_tb_behav.wcfg -log simulate.log"
call xsim  Top_tb_behav -key {Behavioral:sim_1:Functional:Top_tb} -tclbatch Top_tb.tcl -view C:/Users/night/Desktop/EECS443-FinalProject/waveform_generator/Top_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
